### ISSUE TITLE
Can't send transactions after latest update

### ISSUE THREAD

**Issue by laakie** [novacoin-project/novacoin#392] opened 2022-01-23 09:52 UTC
From log:

RPCServer method=sendrawtransaction
ERROR: Non-canonical signature: S value is unnecessarily high
ERROR: CScriptCheck() : d164cc9248 VerifySignature failed
ERROR: ConnectInputs() : d164cc9248 strict VerifySignature failed
ERROR: CTxMemPool::accept() : ConnectInputs failed d164cc9248

got same result with sendtransaction

**Comment by CryptoManiac** [comment] 2022-01-23 20:29
Hi. This issue has been confirmed by other reports. It will be resolved with next update. Thank you for your report.

**Comment by laakie** [comment] 2022-02-04 21:40
Thanks a lot, any eta for the patch ?

**Comment by CryptoManiac** [comment] 2022-02-04 21:42
Issue has been fixed already but there is no release yet. I think this will be done tomorrow.

**Comment by laakie** [comment] 2022-02-04 21:43
Great, thank you very much.
Can we try the "master" repo before release ?

**Comment by CryptoManiac** [comment] 2022-02-04 21:49
I wouldn’t recommend it for now, because few tests are yet to be completed. I’ll close this issue once release will be published.

There is a workaround though. You can repeat sending attempts until signature will satisfy network requirements. Just remember to use RBF to stay safe from double spending attempts by malicious users. Using consequent values of nSequencentor your transactions will guarantee that no double spending is done by your users. Though I would really prefer to wait for real fix instead of relying on workarounds.

**Comment by laakie** [comment] 2022-02-04 21:52
Alright, We'll better wait for the release just to be sure then.

**Closed** 2022-02-11 19:07 UTC
Labels: bug

**Comment by laakie** [comment] 2022-02-11 22:30
all good after updating, thanks again for the great work done
